### PR TITLE
fix: add nodejs support

### PR DESCRIPTION
**Pull request by qkdreyer**

### CODE REVIEW

**Comment by deepnight** [comment]
I get the idea is to disable it for NodeJS, but why? 🤔

**Comment by qkdreyer** [comment]
I'm in the progress of making gameBase networkable using node as the server implementation

**Comment by deepnight** [comment]
👍

**Comment by qkdreyer** [comment]
In case you're interested : https://github.com/qkdreyer/gameBase/tree/networkBase, it only requires https://github.com/HeapsIO/heaps/pull/928

**Pull request merged**
